owner: simboonlong
repo: status
sites:
  - name: Personal website
    url: https://simboonlong.com
  - name: Demo website for utility library
    url: https://utility.simboonlong.com
status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status uptime monitor"
  introMessage: Statuses of various websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/simboonlong/status
workflowSchedule: # https://upptime.js.org/docs/configuration/#ci-schedule, https://upptime.js.org/docs/triggers/#available-workflows, https://en.wikipedia.org/wiki/Cron
  graphs: "0 0 * * 0"
  responseTime: "0 0 * * 0"
  staticSite: "0 0 1 * *"
  summary: "0 0 * * 0"
  updateTemplate: "0 0 1 * *"
  uptime: "0 0 * * 0"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
